/**
 * NexaLink Messaging v2 - Curated Standard Unicode Emoji Dataset
 * Self-hosted, offline-compatible, 0 external runtime dependencies.
 */

export interface EmojiItem {
  emoji: string;
  name: string;
  category: string;
  keywords: string[];
}

export const EMOJI_CATEGORIES = [
  'Smileys & Emotion',
  'Gestures & People',
  'Animals & Nature',
  'Food & Drink',
  'Travel & Places',
  'Activities',
  'Objects',
  'Symbols'
] as const;

export const EMOJI_DATASET: EmojiItem[] = [
  // Smileys & Emotion
  { emoji: '😀', name: 'Grinning Face', category: 'Smileys & Emotion', keywords: ['happy', 'smile', 'grin'] },
  { emoji: '😃', name: 'Grinning Face with Big Eyes', category: 'Smileys & Emotion', keywords: ['happy', 'joy', 'smile'] },
  { emoji: '😄', name: 'Grinning Face with Smiling Eyes', category: 'Smileys & Emotion', keywords: ['happy', 'laugh', 'pleased'] },
  { emoji: '😁', name: 'Beaming Face with Smiling Eyes', category: 'Smileys & Emotion', keywords: ['grin', 'beaming', 'teeth'] },
  { emoji: '😆', name: 'Grinning Squinting Face', category: 'Smileys & Emotion', keywords: ['laugh', 'lol', 'haha'] },
  { emoji: '😅', name: 'Grinning Face with Sweat', category: 'Smileys & Emotion', keywords: ['sweat', 'relief', 'nervous'] },
  { emoji: '😂', name: 'Face with Tears of Joy', category: 'Smileys & Emotion', keywords: ['tears', 'crying laugh', 'lmao'] },
  { emoji: '🤣', name: 'Rolling on the Floor Laughing', category: 'Smileys & Emotion', keywords: ['rofl', 'rotfl', 'hilarious'] },
  { emoji: '😊', name: 'Smiling Face with Smiling Eyes', category: 'Smileys & Emotion', keywords: ['blush', 'warm', 'friendly'] },
  { emoji: '😇', name: 'Smiling Face with Halo', category: 'Smileys & Emotion', keywords: ['angel', 'innocent', 'good'] },
  { emoji: '🙂', name: 'Slightly Smiling Face', category: 'Smileys & Emotion', keywords: ['smile', 'polite', 'okay'] },
  { emoji: '🙃', name: 'Upside-Down Face', category: 'Smileys & Emotion', keywords: ['silly', 'sarcasm', 'irony'] },
  { emoji: '😉', name: 'Winking Face', category: 'Smileys & Emotion', keywords: ['wink', 'flirt', 'joke'] },
  { emoji: '😌', name: 'Relieved Face', category: 'Smileys & Emotion', keywords: ['peaceful', 'calm', 'relieved'] },
  { emoji: '😍', name: 'Smiling Face with Heart-Eyes', category: 'Smileys & Emotion', keywords: ['love', 'crush', 'heart'] },
  { emoji: '🥰', name: 'Smiling Face with Hearts', category: 'Smileys & Emotion', keywords: ['warm', 'adore', 'fond'] },
  { emoji: '😘', name: 'Face Blowing a Kiss', category: 'Smileys & Emotion', keywords: ['kiss', 'affection', 'love'] },
  { emoji: '😋', name: 'Face Savoring Food', category: 'Smileys & Emotion', keywords: ['yum', 'delicious', 'tasty'] },
  { emoji: '😛', name: 'Face with Tongue', category: 'Smileys & Emotion', keywords: ['playful', 'silly', 'tongue'] },
  { emoji: '😜', name: 'Winking Face with Tongue', category: 'Smileys & Emotion', keywords: ['kidding', 'crazy', 'joke'] },
  { emoji: '🤪', name: 'Zany Face', category: 'Smileys & Emotion', keywords: ['goofy', 'wild', 'party'] },
  { emoji: '🤩', name: 'Star-Struck', category: 'Smileys & Emotion', keywords: ['star', 'wow', 'excited'] },
  { emoji: '🥳', name: 'Partying Face', category: 'Smileys & Emotion', keywords: ['celebrate', 'cheers', 'birthday'] },
  { emoji: '😎', name: 'Smiling Face with Sunglasses', category: 'Smileys & Emotion', keywords: ['cool', 'chill', 'sunglasses'] },
  { emoji: '🤓', name: 'Nerd Face', category: 'Smileys & Emotion', keywords: ['geek', 'glasses', 'study'] },
  { emoji: '🧐', name: 'Face with Monocle', category: 'Smileys & Emotion', keywords: ['curious', 'inspect', 'hmm'] },
  { emoji: '🤔', name: 'Thinking Face', category: 'Smileys & Emotion', keywords: ['ponder', 'consider', 'think'] },
  { emoji: '🤫', name: 'Shushing Face', category: 'Smileys & Emotion', keywords: ['quiet', 'secret', 'hush'] },
  { emoji: '🤭', name: 'Face with Hand Over Mouth', category: 'Smileys & Emotion', keywords: ['giggle', 'oops', 'shock'] },
  { emoji: '🤐', name: 'Zipper-Mouth Face', category: 'Smileys & Emotion', keywords: ['silent', 'secret', 'sealed'] },
  { emoji: '🤨', name: 'Face with Raised Eyebrow', category: 'Smileys & Emotion', keywords: ['skeptical', 'doubt', 'suspicious'] },
  { emoji: '😐', name: 'Neutral Face', category: 'Smileys & Emotion', keywords: ['meh', 'straight face', 'blank'] },
  { emoji: '😑', name: 'Expressionless Face', category: 'Smileys & Emotion', keywords: ['unimpressed', 'deadpan', 'bored'] },
  { emoji: '😶', name: 'Face Without Mouth', category: 'Smileys & Emotion', keywords: ['speechless', 'silent', 'no words'] },
  { emoji: '😏', name: 'Smirking Face', category: 'Smileys & Emotion', keywords: ['smirk', 'flirt', 'cheeky'] },
  { emoji: '😒', name: 'Unamused Face', category: 'Smileys & Emotion', keywords: ['annoyed', 'grumpy', 'sigh'] },
  { emoji: '🙄', name: 'Face with Rolling Eyes', category: 'Smileys & Emotion', keywords: ['eye roll', 'whatever', 'frustrated'] },
  { emoji: '😬', name: 'Grimacing Face', category: 'Smileys & Emotion', keywords: ['awkward', 'yikes', 'nervous'] },
  { emoji: '😮', name: 'Face with Open Mouth', category: 'Smileys & Emotion', keywords: ['surprised', 'wow', 'gasp'] },
  { emoji: '😯', name: 'Hushed Face', category: 'Smileys & Emotion', keywords: ['surprised', 'speechless', 'quiet'] },
  { emoji: '😲', name: 'Astonished Face', category: 'Smileys & Emotion', keywords: ['shocked', 'unbelievable', 'amazed'] },
  { emoji: '🥱', name: 'Yawning Face', category: 'Smileys & Emotion', keywords: ['tired', 'sleepy', 'bored'] },
  { emoji: '😴', name: 'Sleeping Face', category: 'Smileys & Emotion', keywords: ['sleep', 'zzz', 'night'] },
  { emoji: '😷', name: 'Face with Medical Mask', category: 'Smileys & Emotion', keywords: ['sick', 'mask', 'hospital'] },
  { emoji: '🤒', name: 'Face with Thermometer', category: 'Smileys & Emotion', keywords: ['fever', 'ill', 'sick'] },
  { emoji: '🤕', name: 'Face with Head-Bandage', category: 'Smileys & Emotion', keywords: ['hurt', 'injury', 'ouch'] },
  { emoji: '🤢', name: 'Nauseated Face', category: 'Smileys & Emotion', keywords: ['gross', 'disgust', 'sick'] },
  { emoji: '🤮', name: 'Face Vomiting', category: 'Smileys & Emotion', keywords: ['puke', 'gross', 'sick'] },
  { emoji: '🤧', name: 'Sneezing Face', category: 'Smileys & Emotion', keywords: ['cold', 'sneeze', 'flu'] },
  { emoji: '🥵', name: 'Hot Face', category: 'Smileys & Emotion', keywords: ['heat', 'sweat', 'summer'] },
  { emoji: '🥶', name: 'Cold Face', category: 'Smileys & Emotion', keywords: ['freeze', 'ice', 'winter'] },
  { emoji: '🥴', name: 'Woozy Face', category: 'Smileys & Emotion', keywords: ['dizzy', 'intoxicated', 'tipsy'] },
  { emoji: '😵', name: 'Dizzy Face', category: 'Smileys & Emotion', keywords: ['faint', 'passed out', 'overwhelmed'] },
  { emoji: '🤯', name: 'Exploding Head', category: 'Smileys & Emotion', keywords: ['mind blown', 'shock', 'insane'] },
  { emoji: '🤠', name: 'Cowboy Hat Face', category: 'Smileys & Emotion', keywords: ['country', 'western', 'howdy'] },
  { emoji: '🥳', name: 'Celebration', category: 'Smileys & Emotion', keywords: ['yay', 'party', 'cheer'] },
  { emoji: '🥺', name: 'Pleading Face', category: 'Smileys & Emotion', keywords: ['puppy eyes', 'begging', 'please'] },
  { emoji: '😢', name: 'Crying Face', category: 'Smileys & Emotion', keywords: ['sad', 'tear', 'upset'] },
  { emoji: '😭', name: 'Loudly Crying Face', category: 'Smileys & Emotion', keywords: ['sobbing', 'bawling', 'grief'] },
  { emoji: '😱', name: 'Face Screaming in Fear', category: 'Smileys & Emotion', keywords: ['scared', 'munch', 'horror'] },
  { emoji: '😖', name: 'Confounded Face', category: 'Smileys & Emotion', keywords: ['frustrated', 'stressed', 'struggle'] },
  { emoji: '😣', name: 'Persevering Face', category: 'Smileys & Emotion', keywords: ['endure', 'trying', 'struggling'] },
  { emoji: '😞', name: 'Disappointed Face', category: 'Smileys & Emotion', keywords: ['sad', 'down', 'bummed'] },
  { emoji: '😓', name: 'Downcast Face with Sweat', category: 'Smileys & Emotion', keywords: ['whew', 'tired', 'down'] },
  { emoji: '😩', name: 'Weary Face', category: 'Smileys & Emotion', keywords: ['exhausted', 'done', 'frustrated'] },
  { emoji: '😫', name: 'Tired Face', category: 'Smileys & Emotion', keywords: ['exhausted', 'whine', 'fed up'] },
  { emoji: '😤', name: 'Face with Steam From Nose', category: 'Smileys & Emotion', keywords: ['huff', 'triumph', 'determined'] },
  { emoji: '😡', name: 'Pouting Face', category: 'Smileys & Emotion', keywords: ['angry', 'mad', 'red face'] },
  { emoji: '😠', name: 'Angry Face', category: 'Smileys & Emotion', keywords: ['mad', 'annoyed', 'furious'] },

  // Gestures & People
  { emoji: '👍', name: 'Thumbs Up', category: 'Gestures & People', keywords: ['like', 'approve', 'yes', 'good', 'agree'] },
  { emoji: '👎', name: 'Thumbs Down', category: 'Gestures & People', keywords: ['dislike', 'no', 'bad', 'disapprove'] },
  { emoji: '👏', name: 'Clapping Hands', category: 'Gestures & People', keywords: ['applause', 'bravo', 'congrats'] },
  { emoji: '🙌', name: 'Raising Hands', category: 'Gestures & People', keywords: ['celebrate', 'hooray', 'praise'] },
  { emoji: '👐', name: 'Open Hands', category: 'Gestures & People', keywords: ['hug', 'open', 'welcome'] },
  { emoji: '🤲', name: 'Palms Up Together', category: 'Gestures & People', keywords: ['prayer', 'ask', 'support'] },
  { emoji: '🤝', name: 'Handshake', category: 'Gestures & People', keywords: ['deal', 'agreement', 'partnership', 'welcome'] },
  { emoji: '🙏', name: 'Folded Hands', category: 'Gestures & People', keywords: ['please', 'thank you', 'namaste', 'hope'] },
  { emoji: '✌️', name: 'Victory Hand', category: 'Gestures & People', keywords: ['peace', 'two', 'v'] },
  { emoji: '🤞', name: 'Crossed Fingers', category: 'Gestures & People', keywords: ['luck', 'hopeful', 'wish'] },
  { emoji: '🤟', name: 'Love-You Gesture', category: 'Gestures & People', keywords: ['love', 'rock on', 'sign'] },
  { emoji: '🤘', name: 'Sign of the Horns', category: 'Gestures & People', keywords: ['rock', 'metal', 'cool'] },
  { emoji: '🤙', name: 'Call Me Hand', category: 'Gestures & People', keywords: ['shaka', 'call', 'surf'] },
  { emoji: '👈', name: 'Backhand Index Pointing Left', category: 'Gestures & People', keywords: ['left', 'point', 'there'] },
  { emoji: '👉', name: 'Backhand Index Pointing Right', category: 'Gestures & People', keywords: ['right', 'point', 'direction'] },
  { emoji: '👆', name: 'Backhand Index Pointing Up', category: 'Gestures & People', keywords: ['up', 'point', 'above'] },
  { emoji: '👇', name: 'Backhand Index Pointing Down', category: 'Gestures & People', keywords: ['down', 'point', 'below'] },
  { emoji: '✋', name: 'Raised Hand', category: 'Gestures & People', keywords: ['stop', 'high five', 'five'] },
  { emoji: '🤚', name: 'Raised Back of Hand', category: 'Gestures & People', keywords: ['hand', 'back'] },
  { emoji: '🖐️', name: 'Hand with Fingers Splayed', category: 'Gestures & People', keywords: ['hand', 'five', 'spread'] },
  { emoji: '👋', name: 'Waving Hand', category: 'Gestures & People', keywords: ['hello', 'bye', 'hi', 'wave'] },
  { emoji: '💪', name: 'Flexed Biceps', category: 'Gestures & People', keywords: ['strong', 'power', 'gym', 'workout'] },
  { emoji: '🦾', name: 'Mechanical Arm', category: 'Gestures & People', keywords: ['robot', 'prosthetic', 'tech'] },
  { emoji: '🧠', name: 'Brain', category: 'Gestures & People', keywords: ['smart', 'intellect', 'thinking', 'mind'] },
  { emoji: '👀', name: 'Eyes', category: 'Gestures & People', keywords: ['look', 'watch', 'peek', 'see'] },
  { emoji: '💯', name: 'Hundred Points', category: 'Gestures & People', keywords: ['perfect', 'score', '100', 'full'] },
  { emoji: '🔥', name: 'Fire', category: 'Gestures & People', keywords: ['lit', 'hot', 'flame', 'awesome'] },
  { emoji: '✨', name: 'Sparkles', category: 'Gestures & People', keywords: ['magic', 'shine', 'clean', 'new'] },
  { emoji: '🎉', name: 'Party Popper', category: 'Gestures & People', keywords: ['congrats', 'party', 'celebration'] },
  { emoji: '❤️', name: 'Red Heart', category: 'Gestures & People', keywords: ['love', 'heart', 'favorite'] },
  { emoji: '💙', name: 'Blue Heart', category: 'Gestures & People', keywords: ['calm', 'support', 'trust'] },
  { emoji: '💜', name: 'Purple Heart', category: 'Gestures & People', keywords: ['kind', 'noble', 'friend'] },
  { emoji: '💡', name: 'Light Bulb', category: 'Gestures & People', keywords: ['idea', 'creative', 'bright', 'smart'] },
  { emoji: '🚀', name: 'Rocket', category: 'Gestures & People', keywords: ['launch', 'fast', 'startup', 'growth'] },
  { emoji: '⭐', name: 'Star', category: 'Gestures & People', keywords: ['favorite', 'rating', 'star'] },
  { emoji: '📌', name: 'Pushpin', category: 'Gestures & People', keywords: ['pin', 'note', 'reminder'] },
  { emoji: '🎯', name: 'Direct Hit', category: 'Gestures & People', keywords: ['target', 'goal', 'bullseye'] },
  { emoji: '🎓', name: 'Graduation Cap', category: 'Gestures & People', keywords: ['education', 'degree', 'alumni', 'vit'] }
];
